### ISSUE TITLE
textarea stops updating after the user types in it

### ISSUE THREAD

**Issue by avh4** [evancz/elm-html#36] opened 2015-01-28 03:36 UTC
As this example shows, it appears that Elm will stop updating a textarea's contents after the textarea is typed in.  If the textarea is replaced with an input, the input works as expected.

In this example, I would expect clicking the button to replace the text in the textarea.  This works until the user types in the textarea, after which clicking the button no longer replaces the text (though the Action does seem to be processed, just the textarea is not correctly updated).

```elm
import Html (..)
import Html.Attributes (..)
import Html.Events (..)
import Signal

-- MODEL

type alias Model = String


-- UPDATE

type Action = NoOp | ReplaceText

update : Action -> Model -> Model
update action model =
    case action of 
        ReplaceText -> "[Button was clicked]"
        NoOp -> model


-- VIEW

view : Model -> Html
view model =
  div []
    [ textarea [cols 60,rows 10] [text model]
--    [ input [value model] []  -- replacing textarea with this input works as expected
    , button [ onClick (Signal.send actionChannel ReplaceText) ] [ text "Button" ]
    ]


-- SIGNALS

main : Signal Html
main =
  Signal.map view model

model : Signal Model
model =
  Signal.foldp update "Initial text" (Signal.subscribe actionChannel)


actionChannel : Signal.Channel Action
actionChannel =
  Signal.channel NoOp
```

**Comment by evancz** [comment] 2015-07-19 22:23
I think this is some oddity of setting things with JS. It seems that if you want to update the content of a `<textarea>` in JS dynamically, you need to set the `.value` property. So the following code works:

```elm
import Html exposing (..)
import Html.Attributes exposing (..)
import Html.Events exposing (..)


-- MODEL

type alias Model = String


-- UPDATE

type Action = NoOp | ReplaceText

update : Action -> Model -> Model
update action model =
    case action of 
        ReplaceText -> "[Button was clicked]"
        NoOp -> model


-- VIEW

view : Model -> Html
view model =
  div []
    [ textarea [ cols 60, rows 10, value model] []
    , button [ onClick actions.address ReplaceText ] [ text "Button" ]
    ]


-- SIGNALS

main : Signal Html
main =
  Signal.map view model


model : Signal Model
model =
  Signal.foldp update "Initial text" actions.signal


actions : Signal.Mailbox Action
actions =
  Signal.mailbox NoOp
```

It will only work once though, but that's because the actual state of the textarea is not being tracked. If the model was being updated on key presses, things would just work.

Given this, I think it is okay to close this issue?

**Comment by evancz** [comment] 2015-10-02 22:57
There has also been a fix in virtual-dom that should definitely address this.

https://github.com/evancz/virtual-dom/pull/23/files

**Closed by evancz** 2015-10-02 22:57 UTC

**Comment by jinjor** [comment] 2016-04-05 10:04
Has this issue already been resolved?

I ran into the same problem at `elm-html 4.0.2`/ `virtual-dom 2.1.0`.

**Comment by pavelhritonenko** [comment] 2016-05-15 20:59
I faced the same issue. Text area stopped updating. Neither `textarea [ value model ] []` and `textarea [] [text model ]` works. If I change it to `input` it works as expected.

**Comment by sbalmer** [comment] 2016-05-29 15:21
I have the same problem. To reproduce:

```
import Html exposing (div, textarea, button, text)
import Html.App exposing (beginnerProgram)
import Html.Events exposing (on, onClick)
import Json.Decode

main =
  beginnerProgram { model = "", view = view, update = update }

view model =
  div []
    [ textarea [ on "change" (Json.Decode.map SetText Html.Events.targetValue)] [ text model ]
    , button [ onClick AddPlus ] [ text "+" ]
    , div [] [ text ("model: " ++ model) ]
    ]

type Msg = AddPlus | SetText String

update msg model =
  case msg of
    AddPlus ->
      model ++ "+"
    SetText t -> t

```

After changing text in the textarea it is not updated anymore.

**Comment by pablohirafuji** [comment] 2016-06-18 22:41
@sbalmer Just follow Evan's suggestion. Instead of using the innerHtml to show the textarea content, use the value attribute:
```
...
import Html.Attributes exposing (value)
import Html.Events exposing (onInput, onClick)
...
view model =
  div []
    [ textarea [ onInput SetText, value model ] []
...
```
